version: '3'

services:
  db:
    image: "mariadb:10.7"
    env_file:
      - .env # set the values in .env for your system
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-h0.0.0.0", "-u$MARIADB_USER", "-p$MARIADB_PASSWORD", "ping", "--silent"]
      interval: 1s
      retries: 120

  proxy:
    image: "nginx:latest"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/proxy.conf:ro"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - http-cb

  web:
    build: .
    environment:
      HOTLINE_CONFIG_PATH: /hotline.yml
      HOTLINE_APP: web
    volumes:
      - "./hotline.yml:/hotline.yml:ro"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
 
  http-cb:
    build: .
    environment:
      HOTLINE_CONFIG_PATH: /hotline.yml
      HOTLINE_APP: http
    volumes:
      - "./hotline.yml:/hotline.yml:ro"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy

  dns-cb:
    build: .
    environment:
      HOTLINE_CONFIG_PATH: /hotline.yml
      HOTLINE_APP: dns
    volumes:
      - "./hotline.yml:/hotline.yml:ro"
      - "./ssl/dns_chal:/acme/response:ro"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy

volumes:
  db-data: