name: Build

on: [push, pull_request]

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    
    - name: Build
      run: |
        go mod download
        go build .
  
  build-spa:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Install Node/npm
      uses: actions/setup-node@v2
      with:
        node-version: "17"
    
    - name: Build
      run: |
        cd spa
        npm i
        npm run build