name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    
    - name: Install Node/npm
      uses: actions/setup-node@v2
      with:
        node-version: "16"
    
    - name: Build
      run: |
        go get .
        pushd internal/app/frontend/spa
        pwd
        echo "testing hello 123"
        npm i
        npm run build
        popd
        go build .