name: Docker Hub Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Get version (workflow_dispatch)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      id: get_version_dispatch
      run: echo "RELEASE_VERSION=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

    - name: Get version (release)
      if: ${{ github.event_name == 'release' }}
      id: get_version_release
      run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/hotline
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        tags: "latest,${{ env.RELEASE_VERSION }}"